# Generated by Django 5.0.7 on 2024-12-17 15:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sofom_project', '0002_listanegra'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_credito',
            name='fecha_otorgamiento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
