PAISES =  ([  
    ('AL', 'Albania'),
    ('DE', 'Alemania'),
    ('AD', 'Andorra'),
    ('AO', 'Angola'),
    ('AG', 'Antigua y Barbuda'),
    ('SA', 'Arabia Saudita'),
    ('DZ', 'Argelia'),
    ('AR', 'Argentina'),
    ('AM', 'Armenia'),
    ('AU', 'Australia'),
    ('AT', 'Austria'),
    ('AZ', 'Azerbaiyán'),
    ('BS', 'Bahamas'),
    ('BH', 'Baréin'),
    ('BD', 'Bangladés'),
    ('BB', 'Barbados'),
    ('BE', 'Bélgica'),
    ('BZ', 'Belice'),
    ('BJ', 'Benín'),
    ('BT', 'Bután'),
    ('BO', 'Bolivia'),
    ('BA', 'Bosnia y Herzegovina'),
    ('BW', 'Botsuana'),
    ('BR', 'Brasil'),
    ('BN', 'Brunéi'),
    ('BG', 'Bulgaria'),
    ('BF', 'Burkina Faso'),
    ('BI', 'Burundi'),
    ('CV', 'Cabo Verde'),
    ('KH', 'Camboya'),
    ('CM', 'Camerún'),
    ('CA', 'Canadá'),
    ('QA', 'Catar'),
    ('TD', 'Chad'),
    ('CL', 'Chile'),
    ('CN', 'China'),
    ('CY', 'Chipre'),
    ('CO', 'Colombia'),
    ('KM', 'Comoras'),
    ('CG', 'Congo'),
    ('CD', 'Congo (República Democrática)'),
    ('KR', 'Corea del Sur'),
    ('KP', 'Corea del Norte'),
    ('CR', 'Costa Rica'),
    ('CI', 'Costa de Marfil'),
    ('HR', 'Croacia'),
    ('CU', 'Cuba'),
    ('DK', 'Dinamarca'),
    ('DM', 'Dominica'),
    ('EC', 'Ecuador'),
    ('EG', 'Egipto'),
    ('SV', 'El Salvador'),
    ('AE', 'Emiratos Árabes Unidos'),
    ('ER', 'Eritrea'),
    ('SK', 'Eslovaquia'),
    ('SI', 'Eslovenia'),
    ('ES', 'España'),
    ('US', 'Estados Unidos'),
    ('EE', 'Estonia'),
    ('ET', 'Etiopía'),
    ('PH', 'Filipinas'),
    ('FI', 'Finlandia'),
    ('FJ', 'Fiyi'),
    ('FR', 'Francia'),
    ('GA', 'Gabón'),
    ('GM', 'Gambia'),
    ('GE', 'Georgia'),
    ('GH', 'Ghana'),
    ('GR', 'Grecia'),
    ('GD', 'Granada'),
    ('GT', 'Guatemala'),
    ('GY', 'Guyana'),
    ('GN', 'Guinea'),
    ('GW', 'Guinea-Bisáu'),
    ('GQ', 'Guinea Ecuatorial'),
    ('HT', 'Haití'),
    ('HN', 'Honduras'),
    ('HU', 'Hungría'),
    ('IN', 'India'),
    ('ID', 'Indonesia'),
    ('IQ', 'Irak'),
    ('IR', 'Irán'),
    ('IE', 'Irlanda'),
    ('IS', 'Islandia'),
    ('IL', 'Israel'),
    ('IT', 'Italia'),
    ('JM', 'Jamaica'),
    ('JP', 'Japón'),
    ('JO', 'Jordania'),
    ('KZ', 'Kazajistán'),
    ('KE', 'Kenia'),
    ('KG', 'Kirguistán'),
    ('KI', 'Kiribati'),
    ('KW', 'Kuwait'),
    ('LA', 'Laos'),
    ('LS', 'Lesoto'),
    ('LV', 'Letonia'),
    ('LB', 'Líbano'),
    ('LR', 'Liberia'),
    ('LY', 'Libia'),
    ('LI', 'Liechtenstein'),
    ('LT', 'Lituania'),
    ('LU', 'Luxemburgo'),
    ('MG', 'Madagascar'),
    ('MY', 'Malasia'),
    ('MW', 'Malaui'),
    ('MV', 'Maldivas'),
    ('ML', 'Malí'),
    ('MT', 'Malta'),
    ('MA', 'Marruecos'),
    ('MH', 'Islas Marshall'),
    ('MU', 'Mauricio'),
    ('MR', 'Mauritania'),
    ('MX', 'México'),
    ('FM', 'Micronesia'),
    ('MD', 'Moldavia'),
    ('MC', 'Mónaco'),
    ('MN', 'Mongolia'),
    ('ME', 'Montenegro'),
    ('MZ', 'Mozambique'),
    ('NA', 'Namibia'),
    ('NR', 'Nauru'),
    ('NP', 'Nepal'),
    ('NI', 'Nicaragua'),
    ('NE', 'Níger'),
    ('NG', 'Nigeria'),
    ('NO', 'Noruega'),
    ('NZ', 'Nueva Zelanda'),
    ('OM', 'Omán'),
    ('NL', 'Países Bajos'),
    ('PK', 'Pakistán'),
    ('PW', 'Palaos'),
    ('PA', 'Panamá'),
    ('PG', 'Papúa Nueva Guinea'),
    ('PY', 'Paraguay'),
    ('PE', 'Perú'),
    ('PL', 'Polonia'),
    ('PT', 'Portugal'),
    ('GB', 'Reino Unido'),
    ('CF', 'República Centroafricana'),
    ('CZ', 'República Checa'),
    ('DO', 'República Dominicana'),
    ('RO', 'Rumania'),
    ('RW', 'Ruanda'),
    ('RU', 'Rusia'),
    ('WS', 'Samoa'),
    ('KN', 'San Cristóbal y Nieves'),
    ('SM', 'San Marino'),
    ('VC', 'San Vicente y las Granadinas'),
    ('LC', 'Santa Lucía'),
    ('ST', 'Santo Tomé y Príncipe'),
    ('SN', 'Senegal'),
    ('RS', 'Serbia'),
    ('SC', 'Seychelles'),
    ('SL', 'Sierra Leona'),
    ('SG', 'Singapur'),
    ('SY', 'Siria'),
    ('SO', 'Somalia'),
    ('LK', 'Sri Lanka'),
    ('SZ', 'Suazilandia'),
    ('ZA', 'Sudáfrica'),
    ('SD', 'Sudán'),
    ('SS', 'Sudán del Sur'),
    ('SE', 'Suecia'),
    ('CH', 'Suiza'),
    ('SR', 'Surinam'),
    ('TH', 'Tailandia'),
    ('TZ', 'Tanzania'),
    ('TJ', 'Tayikistán'),
    ('TL', 'Timor Oriental'),
    ('TG', 'Togo'),
    ('TO', 'Tonga'),
    ('TT', 'Trinidad y Tobago'),
    ('TN', 'Túnez'),
    ('TM', 'Turkmenistán'),
    ('TR', 'Turquía'),
    ('TV', 'Tuvalu'),
    ('UA', 'Ucrania'),
    ('UG', 'Uganda'),
    ('UY', 'Uruguay'),
    ('UZ', 'Uzbekistán'),
    ('VU', 'Vanuatu'),
    ('VE', 'Venezuela'),
    ('VN', 'Vietnam'),
    ('YE', 'Yemen'),
    ('DJ', 'Yibuti'),
    ('ZM', 'Zambia'),
    ('ZW', 'Zimbabue'),])

ANOS_RESIDENCIA = ([    
    ('1', '1 año'),
    ('2', '2 años'),
    ('3', '3 años'),
    ('4', '4 años'),
    ('5', '5 años'),
    ('6', '6 años'),
    ('7', '7 años'),
    ('8', '8 años'),
    ('9', '9 años'),
    ('10', '10 años'),])

TIPO_CREDITO = ([
    ('PF-CICLO 1 (periodo)', 'PF-CICLO 1 (periodo)'),
    ('SISU TE ACOMPAÑA (periodo)', 'SISU TE ACOMPAÑA (periodo)'),
    ('SISU TE ACOMPAÑA (Dia)', 'SISU TE ACOMPAÑA (Dia)'),
    
])

PERIODO = ([
    ('QIN','QUINCENAL'),
    ('MEN','MENSUAL'),
    ('SEM','SEMANAL'),
])




